apiVersion: tekton.dev/v1beta1
kind: Pipeline
  name: customer360-ace-dev
  namespace: customer360
spec:
  tasks:
    - name: git-clone
      params:
        - name: url
          value: 'https://github.com/nmoghadam/customer-api.git'
        - name: revision
          value: main
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:fbf1c4df0f6c1330b34a0ea882ca1dff0e224f3a7060772532a2244438b91074
        - name: userHome
          value: /tekton/home
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-data
  workspaces:
    - name: shared-data
      optional: false
  params: []
  resources: []
  finally: []
